// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pymtbinrjpymamnmhxjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bXRiaW5yanB5bWFtbm1oeGprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDU5NzEsImV4cCI6MjA2MDIyMTk3MX0.VQ-ADm5rzCLJ61cBLHY2atCctDVqt-3IkOGUYKc9H1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);