// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pafzljehoywvefwtvyhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhZnpsamVob3l3dmVmd3R2eWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mzg3ODQsImV4cCI6MjA2MDIxNDc4NH0.zGJQ90Dh8MC_4fz9dE2WNndpUwU5VmfExq9m0RQc3Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);